<?php

/*
  Plugin Name: Newsletter - Automated Newsletters
  Plugin URI: https://www.thenewsletterplugin.com/extensions/automated-extension
  Description: Daily, weekly, monthly autogenerated newsletters with blog latest posts
  Version: 4.7.4
  Author: The Newsletter Team
  Requires at least: 5.6
  Requires PHP: 7.0
  Author URI: https://www.thenewsletterplugin.com
  Disclaimer: Use at your own risk. No warranty expressed or implied is provided.
 */

add_action('newsletter_loaded', function ($version) {
    if (version_compare($version, '8.3.6', '<')) {
        add_action('admin_notices', function () {
            echo '<div class="notice notice-error"><p>Newsletter plugin upgrade required for <strong>Newsletter - Automated Newsletters</strong>.</p></div>';
        });
    } else {
        require_once __DIR__ . '/plugin.php';
        new NewsletterAutomated('4.7.4');
    }
});

register_activation_hook(__FILE__, function () {
    update_option('newsletter_automated_version', '', false);
});

if (!defined('NEWSLETTER_AUTOMATED_TABLE')) {
    global $wpdb;
    define('NEWSLETTER_AUTOMATED_TABLE', $wpdb->prefix . 'newsletter_automated');
}
