<?php
namespace NewsParserPlugin;


return array(
    Controller\EventController::class=>[\ContainerBuilder\DI::class],
    Utils\MenuConfig::class=>[NEWS_PARSER_PLUGIN_DIR.'inc/Config/menu-config.php'],
    Utils\AdapterGuttenberg::class=>[],
    Utils\ResponseFormatter::class=>[],
    Entities\Factory\PostFactory::class=>[],
    Entities\Factory\CronDataFactory::class=>[],
    Parser\XMLParser::class=>[],
    Parser\HTMLRaw::class=>[],
    Parser\HTMLPatternParser::class=>[],
    Models\TemplateModel::class=>[],
    Models\AIOptionsModel::class=>[],
    Models\CronDataModel::class=>[Entities\Factory\CronDataFactory::class],
    Models\PostModel::class=>[Entities\Factory\PostFactory::class],
    Models\PostCacheModel::class=>[],
    Menu\Admin\MenuPage::class=>[Utils\MenuConfig::class],
    Controller\CronTaskController::class=>[Controller\EventController::class,Models\CronDataModel::class],
    Controller\TemplateController::class=>[Models\TemplateModel::class],
    Controller\CronController::class=>[Models\CronDataModel::class],
    Controller\AIOptionsController::class=>[Models\AIOptionsModel::class,[new Service\AI\GeminiAIServiceProvider(),new Service\AI\OpenAIServiceProvider()]],
    Controller\AIController::class=>[['OpenAI'=>new Service\AI\OpenAIServiceProvider(),'Gemini'=>new Service\AI\GeminiAIServiceProvider()]],
    Service\AI\OpenAIServiceProvider::class=>[],
    Service\AI\GeminiAIServiceProvider::class=>[],
    Service\AI\Custom1AIServiceProvider::class=>[],
    Parser\Modifiers\AdapterModifiers\Before\RemoveDublicatedPicturesModifier::class=>[],
    Parser\Modifiers\AdapterModifiers\Before\AddImageSizesModifier::class=>[],
    Parser\Modifiers\AdapterModifiers\Before\RemoveSrcSetAndSizesModifier::class=>[],
    Parser\Modifiers\AdapterModifiers\Before\GroupPicturesModifier::class=>[],
    Parser\Modifiers\AdapterModifiers\Before\AddSourceModifier::class=>[],
    Parser\Modifiers\AdapterModifiers\Before\GenerateImageWithAI::class=>[Service\AI\OpenAIServiceProvider::class],
    Parser\Modifiers\AdapterModifiers\Before\GenerateTitleWithAI::class=>[[new Service\AI\OpenAIServiceProvider(), new Service\AI\GeminiAIServiceProvider()]],
    Parser\Modifiers\AdapterModifiers\Before\GeneratePostBodyWithAI::class=>[[new Service\AI\OpenAIServiceProvider(),new Service\AI\GeminiAIServiceProvider()]],
    Modifiers\RemoveLineBreaks::class=>[],
    Modifiers\ReplaceRelativePathWithAbsolute::class=>[],
    Modifiers\ImagePrepare::class=>[],
    Parser\Modifiers\PostModifiers\AddPostThumbnailModifier::class=>[],
    Controller\PostController::class=>[Parser\HTMLPatternParser::class,Utils\AdapterGuttenberg::class,Models\TemplateModel::class,Models\PostModel::class],
    Controller\ListController::class=>[Parser\XMLParser::class,Models\PostModel::class],
    Controller\VisualConstructorController::class=>[Parser\HTMLRaw::class],
    Controller\MediaController::class=>[Models\PostModel::class],
);